export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const REQUEST_RESTAURANT_PENDING = "REQUEST_RESTAURANT_PENDING";
export const REQUEST_RESTAURANT_SUCCESS = "REQUEST_RESTAURANT_SUCCESS";
export const REQUEST_RESTAURANT_FAILED = "REQUEST_RESTAURANT_PENDING";